<template>
	<div class="aioseo-search-appearance-advanced">
		<core-card
			slug="searchAdvanced"
			:header-text="strings.advanced"
		>
			<core-settings-row
				:name="strings.globalRobotsMeta"
			>
				<template #content>
					<core-robots-meta
						:options="optionsStore.options.searchAppearance.advanced.globalRobotsMeta"
						global
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.sitelinks"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.sitelinks"
						:name="strings.sitelinks"
						:options="[
							{ label: GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.on, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.sitelinksDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="optionsStore.internalOptions.internal.deprecatedOptions.includes('autogenerateDescriptions')"
				:name="strings.autogenerateDescriptions"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.deprecated.searchAppearance.advanced.autogenerateDescriptions"
						name="autogenerateDescriptions"
						:options="[
							{ label: GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.on, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="optionsStore.internalOptions.internal.deprecatedOptions.includes('useContentForAutogeneratedDescriptions') && (!optionsStore.internalOptions.internal.deprecatedOptions.includes('autogenerateDescriptions') || optionsStore.options.deprecated.searchAppearance.advanced.autogenerateDescriptions)"
				:name="strings.useContentForAutogeneratedDescriptions"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.deprecated.searchAppearance.advanced.useContentForAutogeneratedDescriptions"
						name="useContentForAutogeneratedDescriptions"
						:options="[
							{ label: GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.on, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="optionsStore.internalOptions.internal.deprecatedOptions.includes('noPaginationForCanonical')"
				:name="strings.noPaginationForCanonical"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.deprecated.searchAppearance.advanced.noPaginationForCanonical"
						name="noPaginationForCanonical"
						:options="[
							{ label: GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.on, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.useKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.useKeywords"
						name="useKeywords"
						:options="[
							{ label: GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.useKeywordsDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="optionsStore.options.searchAppearance.advanced.useKeywords"
				:name="strings.useCategoriesForMetaKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.useCategoriesForMetaKeywords"
						name="useCategoriesForMetaKeywords"
						:options="[
							{ label: GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.useCategoriesDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="optionsStore.options.searchAppearance.advanced.useKeywords"
				:name="strings.useTagsForMetaKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.useTagsForMetaKeywords"
						name="useTagsForMetaKeywords"
						:options="[
							{ label: GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.useTagsDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="optionsStore.options.searchAppearance.advanced.useKeywords"
				:name="strings.dynamicallyGenerateKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.dynamicallyGenerateKeywords"
						name="dynamicallyGenerateKeywords"
						:options="[
							{ label: GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.dynamicallyGenerateDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				id="description-format"
				v-if="optionsStore.internalOptions.internal.deprecatedOptions.includes('descriptionFormat')"
				:name="strings.descriptionFormat"
				align
			>
				<template #content>
					<core-html-tags-editor
						class="description-format"
						v-model="optionsStore.options.deprecated.searchAppearance.global.descriptionFormat"
						:line-numbers="false"
						single
						:show-tags-description="false"
						tags-context="descriptionFormat"
						:default-tags="[
							'description',
							'site_title',
							'tagline'
						]"
						:show-all-tags-link="true"
					>
						<template #tags-description>
							{{ emptyString }}
						</template>
					</core-html-tags-editor>

					<core-alert
						class="description-notice"
						v-if="!optionsStore.options.deprecated.searchAppearance.global.descriptionFormat.includes('#description')"
						type="red"
					>
						{{ strings.descriptionTagRequired }}
					</core-alert>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.runShortcodes"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.runShortcodes"
						name="runShortcodes"
						:options="[
							{ label: GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.on, value: true }
						]"
					/>

					<core-alert
						class="run-shortcodes-alert"
						v-if="optionsStore.options.searchAppearance.advanced.runShortcodes"
						type="yellow"
						v-html="strings.runShortcodesWarning"
					/>

					<div
						class="aioseo-description"
						v-html="strings.runShortcodesDescription"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.pagedFormat"
				align
			>
				<template #content>
					<core-html-tags-editor
						class="paged-format"
						v-model="optionsStore.options.searchAppearance.advanced.pagedFormat"
						:line-numbers="false"
						single
						tags-context="pagedFormat"
						:default-tags="[
							'page_number'
						]"
						:show-all-tags-link="false"
					>
						<template #tags-description>
							{{ emptyString }}
						</template>
					</core-html-tags-editor>

					<div class="aioseo-description">
						{{ strings.pagedFormatDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="optionsStore.internalOptions.internal.deprecatedOptions.includes('excludePosts')"
				:name="strings.excludePostsPages"
				class="aioseo-exclude-pages-posts"
				align
			>
				<template #content>
					<core-exclude-posts
						:options="optionsStore.options.deprecated.searchAppearance.advanced"
						type="posts"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="optionsStore.internalOptions.internal.deprecatedOptions.includes('excludeTerms')"
				:name="strings.excludeTerms"
				class="aioseo-exclude-terms"
				align
			>
				<template #content>
					<core-exclude-posts
						:options="optionsStore.options.deprecated.searchAppearance.advanced"
						type="terms"
					/>
				</template>
			</core-settings-row>
		</core-card>

		<core-card
			class="aioseo-rss-content-advanced"
			slug="searchAdvancedCrawlCleanup"
			:toggles="optionsStore.options.searchAppearance.advanced.crawlCleanup.enable"
		>
			<template #header>
				<base-toggle
					v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.enable"
				/>

				<span>{{ strings.crawlCleanup }}</span>

				<core-tooltip
					v-if="!optionsStore.options.searchAppearance.advanced.crawlCleanup.enable"
				>
					<svg-circle-question-mark />

					<template #tooltip>
						{{ strings.crawlCleanupDescription }}

						<span
							v-html="links.getDocLink(GLOBAL_STRINGS.learnMore, 'crawlCleanup', true)"
						/>
					</template>
				</core-tooltip>
			</template>

			<div class="aioseo-settings-row aioseo-section-description">
				{{ strings.crawlCleanupDescription }}

				<span
					v-html="links.getDocLink(GLOBAL_STRINGS.learnMore, 'crawlCleanup', true)"
				/>
			</div>

			<core-settings-row
				id="crawl-content-global-feed"
				:name="strings.globalFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.global"
						name="global"
						:options="[
							{ label: GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description"
						v-if="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.global"
					>
						{{ strings.globalFeedDescription }}
						{{ strings.disableGlobalFeedAlert }}

						<div class="rss-link">
							<a
								:href="rootStore.aioseo.urls.feeds.global"
								target="_blank"
							>{{ strings.openYourRssFeed }}</a>

							<a
								class="no-underline"
								:href="rootStore.aioseo.urls.feeds.global"
								target="_blank"
							>&nbsp;<svg-external /></a>
						</div>
					</div>

					<core-alert
						v-if="!optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.global"
						type="red"
					>
						{{ strings.disableGlobalFeedAlert }}
					</core-alert>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.globalCommentsFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.globalComments"
						name="globalComments"
						:options="[
							{ label: GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.globalCommentsFeedDescription }}
					</div>

					<div class="aioseo-description"
						v-if="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.globalComments"
					>
						<a
							:href="rootStore.aioseo.urls.feeds.globalComments"
							target="_blank"
						>{{ strings.openYourCommentsRssFeed }}</a>
						<a
							class="no-underline"
							:href="rootStore.aioseo.urls.feeds.globalComments"
							target="_blank"
						>&nbsp;<svg-external /></a>
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="rootStore.aioseo.data.staticBlogPage"
				:name="strings.staticBlogPageFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.staticBlogPage"
						name="staticBlogPage"
						:options="[
							{ label: GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.staticBlogPageFeedDescription }}
					</div>

					<div class="aioseo-description"
						v-if="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.staticBlogPage"
					>
						<a
							:href="rootStore.aioseo.urls.feeds.staticBlogPage"
							target="_blank"
						>{{ strings.openYourStaticBlogPageFeed }}</a>

						<a
							class="no-underline"
							:href="rootStore.aioseo.urls.feeds.staticBlogPage"
							target="_blank"
						>&nbsp;<svg-external /></a>
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.authorsFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.authors"
						name="authors"
						:options="[
							{ label: GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.authorsFeedDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.postCommentsFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.postComments"
						name="postComments"
						:options="[
							{ label: GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.postCommentsFeedDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.searchFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.search"
						name="search"
						:options="[
							{ label: GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.searchFeedDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.attachmentsFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.attachments"
						name="attachments"
						:options="[
							{ label: GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.attachmentsFeedDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.paginatedFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.paginated"
						name="paginated"
						:options="[
							{ label: GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.paginatedFeedDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="rootStore.aioseo.postData.archives.length"
				:name="strings.postTypesFeed"
			>
				<template #content>
					<base-checkbox
						size="medium"
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.archives.all"
					>
						{{ strings.includeAllPostTypes }}
					</base-checkbox>

					<core-post-type-options
						v-if="!optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.archives.all"
						:options="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds"
						type="archives"
					/>

					<div class="aioseo-description">
						{{ strings.selectPostTypes }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.taxonomiesFeed"
			>
				<template #content>
					<base-checkbox
						size="medium"
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.taxonomies.all"
					>
						{{ strings.includeAllTaxonomies }}
					</base-checkbox>

					<core-post-type-options
						v-if="!optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.taxonomies.all"
						:options="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds"
						type="taxonomies"
					/>

					<div class="aioseo-description">
						{{ strings.selectTaxonomies }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.atomFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.atom"
						name="atom"
						:options="[
							{ label: GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description"
						v-html="strings.atomFeedDescription"
					/>

					<div class="aioseo-description"
						v-if="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.atom"
					>
						<a
							:href="rootStore.aioseo.urls.feeds.atom"
							target="_blank"
						>{{ strings.openYourAtomFeed }}</a>
						<a
							class="no-underline"
							:href="rootStore.aioseo.urls.feeds.atom"
							target="_blank"
						>&nbsp;<svg-external /></a>
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.rdfFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.rdf"
						name="rdf"
						:options="[
							{ label: GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description"
						v-html="strings.rdfFeedDescription"
					/>

					<div class="aioseo-description"
						v-if="optionsStore.options.searchAppearance.advanced.crawlCleanup.feeds.rdf"
					>
						<a
							:href="rootStore.aioseo.urls.feeds.rdf"
							target="_blank"
						>{{ strings.openYourRdfFeed }}</a>
						<a
							class="no-underline"
							:href="rootStore.aioseo.urls.feeds.rdf"
							target="_blank"
						>&nbsp;<svg-external /></a>
					</div>
				</template>
			</core-settings-row>
		</core-card>

		<core-card
			id="aioseo-query-arg-monitoring"
			slug="queryArgLogs"
			:toggles="optionsStore.options.searchAppearance.advanced.blockArgs.enable"
		>
			<template #header>
				<base-toggle
					v-model="optionsStore.options.searchAppearance.advanced.blockArgs.enable"
				/>
				<span>{{ strings.queryArgMonitoring }}</span>
			</template>

			<div class="aioseo-settings-row aioseo-section-description">
				{{ strings.queryArgMonitorDescription }}

				<span
					v-html="links.getDocLink(GLOBAL_STRINGS.learnMore, 'queryArgMonitor', true)"
				/>
			</div>
			<core-settings-row
				:name="strings.logsRetention"
				class="table-retention"
			>
				<template #content>
					<base-select
						size="medium"
						:options="logsRetentionOptions"
						:modelValue="getJsonValue(optionsStore.options.searchAppearance.advanced.blockArgs.logsRetention)"
						@update:modelValue="value => optionsStore.options.searchAppearance.advanced.blockArgs.logsRetention = setJsonValue(value)"
					/>
				</template>
			</core-settings-row>

			<query-arg-monitor-block-arg />

			<query-arg-monitor-table />
		</core-card>
	</div>
</template>

<script>
import { GLOBAL_STRINGS } from '@/vue/plugins/constants'
import links from '@/vue/utils/links'
import {
	useOptionsStore,
	useRootStore
} from '@/vue/stores'

import { useJsonValues } from '@/vue/composables/JsonValues'

import BaseCheckbox from '@/vue/components/common/base/Checkbox'
import BaseRadioToggle from '@/vue/components/common/base/RadioToggle'
import BaseSelect from '@/vue/components/common/base/Select'
import CoreAlert from '@/vue/components/common/core/alert/Index'
import CoreCard from '@/vue/components/common/core/Card'
import CoreExcludePosts from '@/vue/components/common/core/ExcludePosts'
import CoreHtmlTagsEditor from '@/vue/components/common/core/HtmlTagsEditor'
import CorePostTypeOptions from '@/vue/components/common/core/PostTypeOptions'
import CoreRobotsMeta from '@/vue/components/common/core/RobotsMeta'
import CoreSettingsRow from '@/vue/components/common/core/SettingsRow'
import CoreTooltip from '@/vue/components/common/core/Tooltip'
import SvgCircleQuestionMark from '@/vue/components/common/svg/circle/QuestionMark'
import SvgExternal from '@/vue/components/common/svg/External'
import QueryArgMonitorBlockArg from './partials/query-arg-monitor/BlockArg'
import QueryArgMonitorTable from './partials/query-arg-monitor/Table'

import { __, sprintf } from '@/vue/plugins/translations'

const td = import.meta.env.VITE_TEXTDOMAIN

export default {
	setup () {
		const {
			getJsonValue,
			setJsonValue
		} = useJsonValues()

		return {
			GLOBAL_STRINGS,
			getJsonValue,
			links,
			optionsStore : useOptionsStore(),
			rootStore    : useRootStore(),
			setJsonValue
		}
	},
	components : {
		BaseCheckbox,
		BaseRadioToggle,
		BaseSelect,
		CoreAlert,
		CoreCard,
		CoreExcludePosts,
		CoreHtmlTagsEditor,
		CorePostTypeOptions,
		CoreRobotsMeta,
		CoreSettingsRow,
		CoreTooltip,
		SvgCircleQuestionMark,
		SvgExternal,
		QueryArgMonitorBlockArg,
		QueryArgMonitorTable
	},
	data () {
		return {
			emptyString : '',
			strings     : {
				advanced                               : __('Advanced Settings', td),
				globalRobotsMeta                       : __('Global Robots Meta', td),
				autogenerateDescriptions               : __('Autogenerate Descriptions', td),
				useContentForAutogeneratedDescriptions : __('Use Content for Autogenerated Descriptions', td),
				runShortcodes                          : __('Run Shortcodes', td),
				runShortcodesDescription               : sprintf(
					// Translators: 1 - The short plugin name ("AIOSEO"), 2 - "Learn More" link.
					__('This option allows you to control whether %1$s should parse shortcodes when generating data such as the SEO title/meta description. Enabling this setting may cause conflicts with third-party plugins/themes. %2$s', td),
					import.meta.env.VITE_SHORT_NAME,
					links.getDocLink(GLOBAL_STRINGS.learnMore, 'runningShortcodes', true)
				),
				runShortcodesWarning : sprintf(
					// Translators: 1 - "Learn More" link.
					__('NOTE: Enabling this setting may cause conflicts with third-party plugins/themes. %1$s', td),
					links.getDocLink(GLOBAL_STRINGS.learnMore, 'runningShortcodes', true)
				),
				noPaginationForCanonical       : __('No Pagination for Canonical URLs', td),
				useKeywords                    : __('Use Meta Keywords', td),
				useKeywordsDescription         : __('This option allows you to toggle the use of Meta Keywords throughout the whole of the site.', td),
				useCategoriesForMetaKeywords   : __('Use Categories for Meta Keywords', td),
				useCategoriesDescription       : __('Check this if you want your categories for a given post used as the Meta Keywords for this post (in addition to any keywords you specify on the Edit Post screen).', td),
				useTagsForMetaKeywords         : __('Use Tags for Meta Keywords', td),
				useTagsDescription             : __('Check this if you want your tags for a given post used as the Meta Keywords for this post (in addition to any keywords you specify on the Edit Post screen).', td),
				dynamicallyGenerateKeywords    : __('Dynamically Generate Meta Keywords', td),
				dynamicallyGenerateDescription : __('Check this if you want your keywords on your Posts page (set in WordPress under Settings, Reading, Front Page Displays) and your archive pages to be dynamically generated from the keywords of the posts showing on that page. If unchecked, it will use the keywords set in the edit page screen for the posts page.', td),
				pagedFormat                    : __('Paged Format', td),
				pagedFormatDescription         : __('This string gets appended to the titles and descriptions of paginated pages (like term or archive pages).', td),
				descriptionFormat              : __('Description Format', td),
				excludePostsPages              : __('Exclude Posts / Pages', td),
				excludeTerms                   : __('Exclude Terms', td),
				sitelinks                      : __('Enable Sitelinks Search Box', td),
				sitelinksDescription           : sprintf(
					// Translators: 1 - The plugin name ("All in One SEO").
					__('Choose whether %1$s should output the required schema markup that Google needs to generate a sitelinks search box.', td),
					import.meta.env.VITE_SHORT_NAME
				),
				descriptionTagRequired        : __('A Description tag is required in order to properly display your meta descriptions on your site.', td),
				crawlCleanup                  : __('Crawl Cleanup', td),
				queryArgMonitoring            : __('Query Arg Monitoring', td),
				logsRetention                 : __('Logs Retention', td),
				crawlCleanupDescription       : __('Disabling unnecessary RSS feeds can help save search engine crawl quota and speed up content indexing for larger sites. If you choose to disable any feeds, those feed links will automatically redirect to your homepage or applicable archive page.', td),
				queryArgMonitorDescription    : __('This feature allows you to log all query arguments that are used on your site and block them. This will help prevent search engines from crawling every variation of your pages with unrecognized query arguments and help save search engine crawl quota.', td),
				globalFeed                    : __('Global RSS Feed', td),
				globalFeedDescription         : __('The global RSS feed is how users subscribe to any new content that has been created on your site.', td),
				openYourRssFeed               : __('Open Your RSS Feed', td),
				disableGlobalFeedAlert        : __('Disabling the global RSS feed is NOT recommended. This will prevent users from subscribing to your content and can hurt your SEO rankings.', td),
				globalCommentsFeed            : __('Global Comments RSS Feed', td),
				globalCommentsFeedDescription : __('The global comments feed allows users to subscribe to any new comments added to your site.', td),
				openYourCommentsRssFeed       : __('Open Your Comments RSS Feed', td),
				staticBlogPageFeed            : __('Static Posts Page Feed', td),
				staticBlogPageFeedDescription : __('The static posts page feed allows users to subscribe to any new content added to your blog page.', td),
				openYourStaticBlogPageFeed    : __('Open Your Static Posts Page RSS Feed', td),
				authorsFeed                   : __('Author Feeds', td),
				authorsFeedDescription        : __('The authors feed allows your users to subscribe to any new content written by a specific author.', td),
				postCommentsFeed              : __('Post Comment Feeds', td),
				postCommentsFeedDescription   : __('The post comments feed allows your users to subscribe to any new comments on a specific page or post.', td),
				searchFeed                    : __('Search Feed', td),
				searchFeedDescription         : __('The search feed allows visitors to subscribe to your content based on a specific search term.', td),
				attachmentsFeed               : __('Attachments Feed', td),
				attachmentsFeedDescription    : __('The attachments feed allows users to subscribe to any changes to your site made to media file categories.', td),
				postTypesFeed                 : __('Post Type Archive Feeds', td),
				includeAllPostTypes           : __('Include All Post Type Archives', td),
				selectPostTypes               : __('Select which post type archives should include an RSS feed. This only applies to post types that include an archive page.', td),
				taxonomiesFeed                : __('Taxonomy Feeds', td),
				includeAllTaxonomies          : __('Include All Taxonomies', td),
				selectTaxonomies              : __('Select which Taxonomies should include an RSS feed.', td),
				atomFeed                      : __('Atom Feed', td),
				atomFeedDescription           : sprintf(
					// Translators: 1 - Learn more link.
					__('This is a global feed of your site output in the Atom format. %1$s', td),
					links.getPlainLink(GLOBAL_STRINGS.learnMore, 'http://www.atomenabled.org/', true)
				),
				openYourAtomFeed   : __('Open Your Atom Feed', td),
				rdfFeed            : __('RDF/RSS 1.0 Feed', td),
				rdfFeedDescription : sprintf(
					// Translators: 1 - Learn more link.
					__('This is a global feed of your site output in the RDF/RSS 1.0 format. %1$s', td),
					links.getPlainLink(GLOBAL_STRINGS.learnMore, 'https://web.resource.org/rss/1.0/', true)
				),
				openYourRdfFeed          : __('Open Your RDF Feed', td),
				paginatedFeed            : __('Paginated RSS Feeds', td),
				paginatedFeedDescription : __('The paginated RSS feeds are for any posts or pages that are paginated.', td)
			},
			logsRetentionOptions : [
				{ label: __('1 hour', td), value: 'hour' },
				{ label: __('1 day', td), value: 'day' },
				{ label: __('1 week', td), value: 'week' },
				{ label: __('Forever', td), value: 'forever' }
			]
		}
	}
}
</script>

<style lang="scss">
.aioseo-search-appearance-advanced {
	.description-format,
	.paged-format {
		.add-tags {
			margin-top: 0;
		}
	}

	.description-notice {
		margin-top: 10px;
	}

	.run-shortcodes-alert {
		margin-top: 12px;
	}

	svg.aioseo-external {
		width: 14px;
		height: 14px;
		margin-right: 10px;
	}

	.aioseo-alert {
		margin-top: 10px;
	}

	.aioseo-rss-content-advanced,
	#aioseo-query-arg-monitoring {
		.aioseo-settings-row {
			.aioseo-col {
				padding-top: 0;
			}
		}

		.aioseo-description {
			p {
				font-size: 14px;
				line-height: 1.8;
				margin: 8px 0 0;
			}

			div.rss-link {
				margin: 8px 0 0;
			}
		}
	}

	.card-block-query {
		.header {
			height: unset;
		}

		.content {
			padding: 0 !important;
		}
	}

	.table-retention {
		.aioseo-select {
			max-width: 200px;
		}
	}
}
</style>