language: php

matrix:
  fast_finish: true
  global:
    - env: PHPUNIT=global
  include:
    - language: node_js
      node_js:
       - "8.11.3"
      env: GRUNT=yes
  allow_failures:
    - env: WP_MULTISITE=1
    - php: 5.3
      dist: precise
    - php: 5.2
      dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  except:
  - "/^*-v[0-9]/"

install:
  - if [[ $PHPUNIT = "local" ]]; then composer install; fi
  - if [[ $GRUNT = "yes" ]]; then chmod +x bin/init-grunt.sh;bin/init-grunt.sh; fi

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
  - if [[ $GRUNT = "yes" ]]; then grunt; fi
  - if [[ $PHPUNIT = "local" ]]; then ./vendor/bin/phpunit; else phpunit; fi

after_failure:
- cat "logs/phpcs.log"
- cat "logs/jslogs.log"